{"name": "test_tc_002_Login_Logout_invalid_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False", "trace": "fixture_code = None\n\n    def test_tc_002_Login_Logout_invalid_login(fixture_code):\n        print('This is my test case code...')\n        print('Test case is unsuccessful with incorrect login...')\n>       assert actual_result == False\nE       assert True == False\n\nAutomationCases\\test_TC_001_First_Test_case.py:34: AssertionError"}, "attachments": [{"name": "stdout", "source": "6085e5aa-8d0a-49bd-8a2e-7da08dca0bec-attachment.txt", "type": "text/plain"}], "start": 1674490125523, "stop": 1674490125523, "uuid": "1eb7a24c-edc4-406f-8bfe-76f12795683c", "historyId": "7058015752e5b13b2b79eb2bce827edb", "testCaseId": "870ce409095430eb4d62fbe5bcd1828c", "fullName": "test_TC_001_First_Test_case#test_tc_002_Login_Logout_invalid_login", "labels": [{"name": "suite", "value": "test_TC_001_First_Test_case"}, {"name": "host", "value": "__VK__"}, {"name": "thread", "value": "24868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_TC_001_First_Test_case"}]}