{"name": "test_tc_004_Login_Logout_invalid_login_and_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False", "trace": "def test_tc_004_Login_Logout_invalid_login_and_password():\n        print('This is my test case code...')\n        print('Test case is finished unsuccessful with wrong password...')\n>       assert actual_result == False\nE       assert True == False\n\nAutomationCases\\test_TC_001_First_Test_case.py:44: AssertionError"}, "attachments": [{"name": "stdout", "source": "8f4a9f8a-6741-4e72-88cf-e10349bd2ce8-attachment.txt", "type": "text/plain"}], "start": 1674489872570, "stop": 1674489872570, "uuid": "f4da477d-28f3-45cb-81c0-a666b8ef816d", "historyId": "96e854564203867f424847fea3d886a6", "testCaseId": "0de41931881161326334a3884e6918af", "fullName": "test_TC_001_First_Test_case#test_tc_004_Login_Logout_invalid_login_and_password", "labels": [{"name": "suite", "value": "test_TC_001_First_Test_case"}, {"name": "host", "value": "__VK__"}, {"name": "thread", "value": "3560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_TC_001_First_Test_case"}]}