{"name": "test_tc_004_Login_Logout_invalid_login_and_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False", "trace": "def test_tc_004_Login_Logout_invalid_login_and_password():\n        print('This is my test case code...')\n        print('Test case is finished unsuccessful with wrong password...')\n>       assert actual_result == False\nE       assert True == False\n\nAutomationCases\\test_TC_001_First_Test_case.py:44: AssertionError"}, "attachments": [{"name": "stdout", "source": "cd3ead01-b311-4361-866e-a8cb89f8163b-attachment.txt", "type": "text/plain"}], "start": 1674490125583, "stop": 1674490125583, "uuid": "6145afd2-abe9-43ee-a512-72472083bce2", "historyId": "96e854564203867f424847fea3d886a6", "testCaseId": "0de41931881161326334a3884e6918af", "fullName": "test_TC_001_First_Test_case#test_tc_004_Login_Logout_invalid_login_and_password", "labels": [{"name": "suite", "value": "test_TC_001_First_Test_case"}, {"name": "host", "value": "__VK__"}, {"name": "thread", "value": "24868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_TC_001_First_Test_case"}]}