{"name": "test_tc_002_Login_Logout_invalid_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False", "trace": "fixture_code = None\n\n    def test_tc_002_Login_Logout_invalid_login(fixture_code):\n        print('This is my test case code...')\n        print('Test case is unsuccessful with incorrect login...')\n>       assert actual_result == False\nE       assert True == False\n\nAutomationCases\\test_TC_001_First_Test_case.py:34: AssertionError"}, "attachments": [{"name": "stdout", "source": "674072c0-57f9-4784-ae72-51727db8666d-attachment.txt", "type": "text/plain"}], "start": 1674489872506, "stop": 1674489872506, "uuid": "2002f1dc-f147-49ed-974f-471dc675f82e", "historyId": "7058015752e5b13b2b79eb2bce827edb", "testCaseId": "870ce409095430eb4d62fbe5bcd1828c", "fullName": "test_TC_001_First_Test_case#test_tc_002_Login_Logout_invalid_login", "labels": [{"name": "suite", "value": "test_TC_001_First_Test_case"}, {"name": "host", "value": "__VK__"}, {"name": "thread", "value": "3560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_TC_001_First_Test_case"}]}